name: Project tests

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  linters:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.1]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build tsconfig
        run: npx gulp build:tsconfig

      - name: Run tests
        run: npm test
